name: 'Elasticsearch'

on: push

jobs:

    integration:
        name: ES ${{ matrix.elasticsearch }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                elasticsearch: [ '7.11.2', '6.8.14' ]
        steps:
            -   name: Configure sysctl limits
                run: |
                    sudo swapoff -a
                    sudo sysctl -w vm.swappiness=1
                    sudo sysctl -w fs.file-max=262144
                    sudo sysctl -w vm.max_map_count=262144

            -   name: Runs Elasticsearch
                uses: elastic/elastic-github-actions/elasticsearch@master
                with:
                    stack-version: ${{ matrix.elasticsearch }}
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2
                    extensions: 'json, curl'
            -   name: Prepare cache
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Integration tests
                run: 'composer test:integration'
