name: 'Mutations'

on: push

jobs:

    infection:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    extensions: 'json, pcov'
            -   name: Prepare cache
                id: composer-cache
                run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Mutation tests
                env:
                    INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
                run: 'php vendor/bin/infection --test-framework-options="--testsuite=unit" -s --min-msi=95 --min-covered-msi=95'
