name: CI

on: push

jobs:

    psalm:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    tools: composer:v2
                    extensions: 'json'
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Static analysing
                run: 'php vendor/bin/psalm --output-format=github --long-progress'

    unit:
        name: Unit tests PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0', '7.4' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    extensions: 'json, pcov'
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Unit tests
                run: php vendor/bin/phpunit --testsuite=unit --coverage-text

    integration:
        name: Integration tests ES ${{ matrix.elasticsearch }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                elasticsearch: [ '7.11.2', '6.8.14' ]
                # elasticsearch: [ '7.11.2', '6.8.14', '5.6' ]
        services:
            elasticsearch:
                image: elasticsearch:${{ matrix.elasticsearch }}
                ports:
                    - 9200:9200
                env:
                    discovery.type: single-node
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2
                    extensions: 'json, curl'
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Unit tests
                run: php vendor/bin/phpunit --testsuite=integration --no-coverage
