name: CI

on: push

jobs:

    psalm:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    tools: composer:v1
                    extensions: 'json'
            -   name: Install dependencies
                run: 'composer install --no-scripts --prefer-dist'
            -   name: Static analysing
                run: 'php vendor/bin/psalm --output-format=github --long-progress'

    php-unit:
        name: Tests (PHP ${{ matrix.php }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0', '7.4']
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v1
                    extensions: 'json, pcov'
            -   name: Install dependencies
                run: 'composer install --no-scripts --prefer-dist'
            -   name: Unit tests
                run: php vendor/bin/phpunit --coverage-text
