name: 'CI / Unit tests'

on: push

jobs:

    unit:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0', '7.4' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    extensions: 'json, pcov'
            -   name: Prepare cache
                id: composer-cache
                run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: 'composer install -q -n --no-scripts --prefer-dist'
            -   name: Unit tests
                run: 'php vendor/bin/phpunit --testsuite=unit --coverage-text --coverage-clover coverage.xml'
            -   name: Upload coverage
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
